USE [master]
GO
/****** Object:  Database [TesteRemoto]    Script Date: 06/04/2020 09:47:07 ******/
CREATE DATABASE [TesteRemoto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TesteRemoto', FILENAME = N'D:\Projetos\TesteRemoto\Banco\TesteRemoto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TesteRemoto_log', FILENAME = N'D:\Projetos\TesteRemoto\Banco\TesteRemoto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TesteRemoto] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TesteRemoto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TesteRemoto] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TesteRemoto] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TesteRemoto] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TesteRemoto] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TesteRemoto] SET ARITHABORT OFF 
GO
ALTER DATABASE [TesteRemoto] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TesteRemoto] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TesteRemoto] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TesteRemoto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TesteRemoto] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TesteRemoto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TesteRemoto] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TesteRemoto] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TesteRemoto] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TesteRemoto] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TesteRemoto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TesteRemoto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TesteRemoto] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TesteRemoto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TesteRemoto] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TesteRemoto] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TesteRemoto] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TesteRemoto] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TesteRemoto] SET  MULTI_USER 
GO
ALTER DATABASE [TesteRemoto] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TesteRemoto] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TesteRemoto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TesteRemoto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TesteRemoto] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TesteRemoto] SET QUERY_STORE = OFF
GO
USE [TesteRemoto]
GO
/****** Object:  UserDefinedDataType [dbo].[Id]    Script Date: 06/04/2020 09:47:07 ******/
CREATE TYPE [dbo].[Id] FROM [bigint] NOT NULL
GO
/****** Object:  Table [dbo].[Sexos]    Script Date: 06/04/2020 09:47:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sexos](
	[SexoId] [dbo].[Id] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Sexos] PRIMARY KEY CLUSTERED 
(
	[SexoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 06/04/2020 09:47:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[UsuarioId] [dbo].[Id] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](200) NOT NULL,
	[DataNascimento] [date] NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Senha] [varchar](30) NOT NULL,
	[Ativo] [smallint] NOT NULL,
	[SexoId] [dbo].[Id] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[UsuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios_Sexos] FOREIGN KEY([SexoId])
REFERENCES [dbo].[Sexos] ([SexoId])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK_Usuarios_Sexos]
GO

INSERT INTO Sexos(Descricao) values('Masculino')
INSERT INTO Sexos(Descricao) values('Feminino')
GO

USE [master]
GO
ALTER DATABASE [TesteRemoto] SET  READ_WRITE 
GO
